// @ts-check
// FreeSWITCH Users Manual sidebar — fully autogenerated from the docs/ tree.
//
// Drop a new .mdx into any part folder and it appears automatically, both in
// the sidebar and in that folder's <DocCardList /> index page. Each folder's
// `index.mdx` is auto-used as the category landing page (and excluded from the
// child list). Category labels + order come from each folder's `_category_.json`;
// chapter order within a category comes from each doc's `sidebar_position`.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manual: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
