// @ts-check
// Explicit sidebar for the FreeSWITCH Users Manual, ordered as a manual rather
// than autogenerated. Parts use Arabic numerals.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manual: [
    "index",
    {
      type: "category",
      label: "Part 1: Foundations",
      link: { type: "generated-index", slug: "/part-1-foundations" },
      items: ["foundations/introduction", "foundations/getting-started"],
    },
    {
      type: "category",
      label: "Part 2: The Configuration System",
      link: { type: "generated-index", slug: "/part-2-configuration-system" },
      items: [
        "configuration-system/xml-configuration",
        "configuration-system/variables-and-core-settings",
        "configuration-system/module-loading",
      ],
    },
    {
      type: "category",
      label: "Part 3: Users and Endpoints",
      link: { type: "generated-index", slug: "/part-3-users-and-endpoints" },
      items: [
        "users-endpoints/user-directory",
        "users-endpoints/sip-profiles-sofia",
        "users-endpoints/gateways",
        "users-endpoints/webrtc-verto",
        "users-endpoints/webrtc-sip-wss",
        "users-endpoints/other-endpoints",
      ],
    },
    {
      type: "category",
      label: "Part 4: Call Routing and the Dialplan",
      link: { type: "generated-index", slug: "/part-4-dialplan" },
      items: [
        "dialplan/xml-dialplan",
        "dialplan/inbound-public-context",
        "dialplan/dptools-reference",
        "dialplan/time-and-condition-routing",
      ],
    },
    {
      type: "category",
      label: "Part 5: Media and Codecs",
      link: { type: "generated-index", slug: "/part-5-media-and-codecs" },
      items: [
        "media/codecs-and-negotiation",
        "media/media-handling",
        "media/audio-files-and-streaming",
      ],
    },
    {
      type: "category",
      label: "Part 6: Applications and Features",
      link: { type: "generated-index", slug: "/part-6-applications" },
      items: [
        "applications/voicemail",
        "applications/conferencing",
        "applications/ivr-menus",
        "applications/queues-fifo-callcenter",
        "applications/utility-applications",
        "applications/fax-t38",
      ],
    },
    {
      type: "category",
      label: "Part 7: Integration and Control",
      link: { type: "generated-index", slug: "/part-7-integration" },
      items: [
        "integration/event-socket",
        "integration/xml-curl",
        "integration/call-detail-records",
        "integration/scripting",
        "integration/access-control-lists",
        "integration/signalwire",
      ],
    },
    {
      type: "category",
      label: "Part 8: Reference",
      link: { type: "generated-index", slug: "/part-8-reference" },
      items: [
        "reference/cli-and-api",
        "reference/channel-variables",
        "reference/appendix-vanilla-config-map",
        "reference/appendix-codec-table",
        "reference/appendix-glossary",
      ],
    },
  ],
};

module.exports = sidebars;
